disabled_rules:
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - nesting
  - orphaned_doc_comment
opt_in_rules:
  - explicit_init
included:
  - Sources
  - Tests
excluded:
  - .build
type_name:
  allowed_symbols: ["_"]
